provider: "akshare_eastmoney"
bars_dir: "data/bars_1m"
start_date: "2025-12-01"
end_date: "2026-01-14"
symbols:
  # 先别全市场，先跑 20-50 只，确保链路通
  - "600000"
  - "600519"
  - "300750"
  - "000001"
  - "000651"
  - "002415"
  - "002594"
  - "601318"
  - "601888"
  - "603986"
